apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_S3_ENDPOINT: aHR0cDovL21pbmlvLmljLXNoYXJlZC1taW5pby5zdmMuY2x1c3Rlci5sb2NhbDo5MDAw
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: ic-shared-db
    app.kubernetes.io/instance: ic-shared-database-app
    component: ic-shared-db
  name: secret-minio
type: Opaque
