apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: shared-database
    app.kubernetes.io/instance: database-app
    component: shared-database
  name: shared-database
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: shared-database
    component: shared-database
  sessionAffinity: None
  type: ClusterIP
