apiVersion: v1
data:
  database-name: ZGVtb2Ri
  database-password: ZGVtb2Ri
  database-user: ZGVtb2Ri
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: shared-database
    app.kubernetes.io/instance: database-app
    component: shared-database
  name: demodb
type: Opaque
