apiVersion: v1
data:
  default.yaml: "# Copyright (C) 2019-2021 Zilliz. All rights reserved.\n#\n# Licensed
    under the Apache License, Version 2.0 (the \"License\"); you may not use this
    file except in compliance\n# with the License. You may obtain a copy of the License
    at\n#\n# http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable
    law or agreed to in writing, software distributed under the License\n# is distributed
    on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express\n#
    or implied. See the License for the specific language governing permissions and
    limitations under the License.\n\netcd:\n  endpoints:\n    - vectordb-etcd:2379\n\nmetastore:\n
    \ type: etcd\n\nminio:\n  address: minio.ic-shared-minio.svc.cluster.local\n  port:
    9000\n  accessKeyID: minio\n  secretAccessKey: minio123\n  useSSL: false\n  bucketName:
    milvus-bucket\n  rootPath: file\n  useIAM: false\n  iamEndpoint: \n  region: \n
    \ useVirtualHost: false\n\nmq:\n  type: rocksmq\n\nmessageQueue: rocksmq\n\nrootCoord:\n
    \ address: localhost\n  port: 53100\n  enableActiveStandby: false  # Enable rootcoord
    active-standby\n\nproxy:\n  port: 19530\n  internalPort: 19529\n\nqueryCoord:\n
    \ address: localhost\n  port: 19531\n  enableActiveStandby: false  # Enable querycoord
    active-standby\n\nqueryNode:\n  port: 21123\n  enableDisk: true # Enable querynode
    load disk index, and search on disk index\n\nindexCoord:\n  address: localhost\n
    \ port: 31000\n  enableActiveStandby: false  # Enable indexcoord active-standby\n\nindexNode:\n
    \ port: 21121\n  enableDisk: true # Enable index node build disk vector index\n\ndataCoord:\n
    \ address: localhost\n  port: 13333\n  enableActiveStandby: false  # Enable datacoord
    active-standby\n\ndataNode:\n  port: 21124\n\nlog:\n  level: info\n  file:\n    rootPath:
    \"\"\n    maxSize: 300\n    maxAge: 10\n    maxBackups: 20\n  format: text"
  user.yaml: |-
    #    For example enable rest http for milvus proxy
    #    proxy:
    #      http:
    #        enabled: true
    ##  Enable tlsMode and set the tls cert and key
    #  tls:
    #    serverPemPath: /etc/milvus/certs/tls.crt
    #    serverKeyPath: /etc/milvus/certs/tls.key
    #   common:
    #     security:
    #       tlsMode: 1
    common:
      security:
        authorizationEnabled: true
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: milvus
    app.kubernetes.io/instance: milvus
    component: milvus
  name: vectordb-milvus
