apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: ic-shared-milvus
    app.kubernetes.io/name: milvus
    app.kubernetes.io/version: 2.4.0
    argocd.argoproj.io/managed-by: openshift-gitops
    component: milvus
  name: vectordb-milvus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
