apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app.kubernetes.io/instance: ic-shared-milvus
    app.kubernetes.io/name: etcd
    argocd.argoproj.io/managed-by: openshift-gitops
    component: milvus
  name: vectordb-etcd-headless
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: client
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: peer
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: vectordb
    app.kubernetes.io/name: etcd
    component: milvus
  sessionAffinity: None
  type: ClusterIP
