apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  annotations:
    argocds.argoproj.io/name: openshift-gitops
    argocds.argoproj.io/namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-grafana
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-argocd-grafana
roleRef:
  name: openshift-gitops-argocd-grafana
  namespace: ic-shared-db
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-grafana
  namespace: openshift-gitops
userNames:
- system:serviceaccount:openshift-gitops:openshift-gitops-argocd-grafana
