apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: openshift-gitops
    app.kubernetes.io/part-of: argocd
  name: openshift-gitops-argocd-redis
rules:
- apiGroups:
  - security.openshift.io
  attributeRestrictions: null
  resourceNames:
  - nonroot-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
