apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: ic-shared-db
    app.kubernetes.io/instance: ic-shared-database-app
    component: ic-shared-db
  name: claimdb
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: ic-shared-db
    component: ic-shared-db
  sessionAffinity: None
  type: ClusterIP
